### ISSUE TITLE
GQ-EMF 390v2 Re 3.72 changed SPIR response. Exception in SPIR : Invalid SPI data chunk at address 0x14 : b'Z\x02'

### ISSUE THREAD

**Issue by AJRepo** [bernardn/python-libgqe#20]
Thanks for releasing a very nice opensource program. 

I was attempting to use it on the GQ-EMF 390v2 Re 3.72 and was getting the error after reading the first record of 

`Exception in SPIR : Invalid SPI data chunk at address 0x14 : b'Z\x02'`

I checked using just a raw dump of the data and it appears that Re 3.72 has an undocumented change to what's returned by SPIR to add two more bytes, so instead of a 12 byte data grab, you now need 14. 

A sample grab of raw data ( See https://github.com/AJRepo/gq_emf_scripts ) gives us raw data 

```
55aa1705100e3737
aa550013404f8042c43119485a02
aa550013404f8042c43119485a02
aa550013404f8042c43119485a02
aa550013404f8042c43119485a02
aa550013ce1f8142ab9c0b485a02
aa5500148d567e42947efc475a08
aa55001362cc8042947efc475a08
aa55001365fd7e4280b721485a02
aa55001321037e420e021e485a02
aa550013f6788042947efc475a08
...
```

Looks like the 5a 02 is a new field "possible source"

https://www.gqelectronicsllc.com/forum/topic.asp?TOPIC_ID=9175

```
// Possible Source
char sbuf[16];
memset(sbuf,0,16);
if(DATA[i] == 0x5A)
{
unsigned char s = DATA[i+1];
i+=2;
if(s == 0) sprintf(sbuf, "---");
else if(s == 1) sprintf(sbuf, "Smart Meter");
else if(s == 2) sprintf(sbuf, "Cell Tower");
else if(s == 3) sprintf(sbuf, "Microwave");
else if(s == 4) sprintf(sbuf, "WiFi/Phone");
else if(s == 5) sprintf(sbuf, "Static");
else if(s == 6) sprintf(sbuf, "AC EF");
else if(s == 7) sprintf(sbuf, "Power Line");
else sprintf(sbuf, "Mixed");
}
```

Looks like libgqe/protocol/GQRFC1701/v1_00/SPIR.py is where it specifies 12 bytes for each data grab. 

Wondering if you can help with that update? 

Thanks!

**Comment by AJRepo** [comment]
I tried changing the number of data bytes read from 12 to 14 

`pdb += 14`

and testing to see if there are 14 or more bytes to read

`if lnd - pdb >= 14:`

but that gives 

> Reading address 0x008000
> Exception in SPIR : index out of range

so perhaps at around 8000 there's a missing byte? 

changing that to 

`if lnd - pdb >= 15:`

looks like it works. Full git diff is 

$ git diff libgqe/protocol/GQRFC1701/v1_00/SPIR.py 
```
diff --git a/libgqe/protocol/GQRFC1701/v1_00/SPIR.py b/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
index c0b6575..bb2dd24 100644
--- a/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
+++ b/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
@@ -46,17 +46,18 @@ class SPIR(SPIR_PROTO):
                 else:
                     break
             elif data[pdb:pdb+2] == b'\xaa\x55':  # Data
-                if lnd - pdb >= 12:
+                if lnd - pdb >= 15:
                     emf = (data[pdb+2] * 16 + data[pdb+3] >> 4) + (data[pdb+3] & 15) / 10
                     ef = struct.unpack('<f', data[pdb+4:pdb+8])[0]
                     rf = struct.unpack('<f', data[pdb+8:pdb+12])[0]
+                    ft = data[pdb+13] + data[pdb+14]
                     yield {
                         'ts': datetime.datetime.fromtimestamp(ts),
                         'emf': emf, 'emf-unit': 'mG',
                         'ef': ef, 'ef-unit': 'V/m',
                         'rf': rf, 'rf-unit': 'pW/cm2'
                     }
-                    pdb += 12
+                    pdb += 14
                     ts += 1
                 else:
                     break

```

**Comment by bernardn** [comment]
Hi,

Thank you for pointing on this issue.

I created a PR #22 containing changes that should add support for this feature, which differs from your proposal, since it'd break the functionality for older devices whose records are only 12 bytes in length.

Could you please check that the changes are functional on your device ?

Alternatively, you can provide me with a SPI dump after having checked out the latest code  :
`./gqe-cli [your-serial-device] --spi-get --out-file spi-dump.dat --format raw`

Thank you.

**Comment by AJRepo** [comment]
Thanks! Working from e0337b2ca1b1de5999a68653a61ae52978ab8efb ... 

$ ./gqe-cli --spi-get --out-file spi-dump.tab --unit GQEMF390 --revision "Re 3.72" /dev/ttyUSB0 

results in 

```
Reading address 0x000000
Exception in SPIR : Invalid SPI data chunk at address 0x14 : b'Z\x02'
```


Attached is a raw dump using `--format raw`
[spi-dump.dat.gz](https://github.com/bernardn/python-libgqe/files/11594496/spi-dump.dat.gz)

**Comment by AJRepo** [comment]
Solved the Invalid SPI data chunk at address 0x14 : b'Z\x02' issue with changing
```
--- a/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
+++ b/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
-                    if lnd - pdb >= 14 and data[pdb+12] == b'\x5a':  # Source
+                    if lnd - pdb >= 14 and data[pdb+12] != b'\xaa\x55':  # Source
```

Solved the "ord expects a string, integer found" issue with 
```
-                            src = self.SRC[ord(data[pdb + 13])]
+                            src = self.SRC[data[pdb + 13]]
```

but now have an issue where the length of each parsed data is about 4k, but from time to time at the end of a data block the data wraps to the next entry. 

Before, you had a break statement, when there wasn't enough data in the data[] array, but now when there isn't enough data in data[] it can be 12 bytes long  which is fine for the older version, but now throws an error if `lnd - pdb == 12` of

Reading address 0x002000
Exception in SPIR : Invalid SPI data chunk at address 0x0 : b'Z\x02'

When it sees a line exactly 12 byes long it tries to run as the older version, tries to parse, and fails.

Here's an output of the data in that decode_spi_chunk loop and note that when pdb goes back 
to 0 that aa55 is not the start of the data/

```
pdb=4062,lnd=4102, len(data)=14
data[pdb:pdb+14]= b'aa55 0008 6666 e63f 652f 4148 5a02'

pdb=4076,lnd=4102, len(data)=14
data[pdb:pdb+14]= b'aa55 0008 cdcc 0c40 6e15 bd48 5a02'

pdb=4090,lnd=4102, len(data)=12
data[pdb:pdb+14]= b'aa55 0008 9a99 1940 4fb7 4548'

pdb=0,lnd=4096, len(data)=14
data[pdb:pdb+14]= b'5a02 aa55 0008 0000 0040 652f 4148'

```

**Comment by bernardn** [comment]
Thank you for the test and the dump.
I just updated the branch with relevant fixes (39f6d544f0cc931562d0602c73d50f9b86bb7611), the code now decodes your dump as expected.
Could you please check if it's now alright, as well as if the source identification is consistent with your measurements ?
Thanks again for your collaboration !

edits: 
- Updated Commit ID
- Also, would you be kind enough to provide me with your device's identification string ?
`./gqe-cli  [/your-serial-device] --get-identity`

**Comment by AJRepo** [comment]
Thank you for the update. 

The data comes in except when there is a 12 byte string at the end of a data array when it throws

```
Reading address 0x002000
Exception in SPIR : Invalid SPI data chunk at address 0x0 : b'Z\x02'
```

Running the --get-identity flag gives

```
$ ./gqe-cli --get-identity  /dev/ttyUSB0
None : The specified unit model is unknown to this software.
```

but you can get around that with additional flags as

```
$  ./gqe-cli --get-identity  --unit GQEMF390 --revision "Re 3.72" /dev/ttyUSB0
GQ-EMF390 v2Re 3. 300b3339313694
```

**Comment by AJRepo** [comment]
Works perfectly with this change

```
diff --git a/libgqe/protocol/GQRFC1701/v1_00/SPIR.py b/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
index 5bc6ce2..ce008e4 100644
--- a/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
+++ b/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
@@ -57,7 +57,7 @@ class SPIR(SPIR_PROTO):
                 else:
                     break
             elif data[pdb:pdb+2] == b'\xaa\x55':  # Data
-                if lnd - pdb >= 12:
+                if lnd - pdb >= 14:
                     emf = (data[pdb+2] * 16 + data[pdb+3] >> 4) + (data[pdb+3] & 15) / 10
                     ef = struct.unpack('<f', data[pdb+4:pdb+8])[0]
                     rf = struct.unpack('<f', data[pdb+8:pdb+12])[0]

```
but I know that would break older versions.

**Comment by AJRepo** [comment]
Some timestamps seem to also be misread. 

For example this command 

```
./gqe-cli --spi-get  --format csv --unit GQEMF390 --revision "Re 3.72" /dev/ttyUSB0
```

reports unixtime=00000000 starting at line  292 

```
... line 290 ...
2023-05-19 09:41:37;1.0;mG;2.799999952316284;V/m;297879.25;pW/cm2;Microwave;
1969-12-31 18:00:00;0.9;mG;2.4000000953674316;V/m;311998.5625;pW/cm2;Microwave;
1969-12-31 18:00:01;0.9;mG;2.5999999046325684;V/m;212068.375;pW/cm2;Microwave;
1969-12-31 18:00:02;0.9;mG;2.4000000953674316;V/m;204031.75;pW/cm2;Microwave;
1969-12-31 18:00:03;1.0;mG;2.4000000953674316;V/m;196298.6875;pW/cm2;Microwave;
...
```

but then resolves 66 lines later. 

```
...line 356 ...
1969-12-31 18:01:05;0.9;mG;2.200000047683716;V/m;204031.75;pW/cm2;Microwave;
1969-12-31 18:01:06;0.9;mG;3.0;V/m;314415.875;pW/cm2;Microwave;
2023-05-19 09:42:45;0.9;mG;2.4000000953674316;V/m;210436.21875;pW/cm2;Microwave;
2023-05-19 09:42:46;0.9;mG;2.5999999046325684;V/m;210436.21875;pW/cm2;Microwave;
```

**Comment by bernardn** [comment]
A different approach will be needed for processing the chunks (maximum data length that can be read at once), as it happens impossible to reliably process both 12 and 14-bytes data this way. Indeed, the first chunk ends with 12-bytes data, leaving the remaining 2 ones in the beginning of the next one. The 12 bytes have the code consider them a whole set, when they are not.

Unfortunately, the changes GQE brought to the protocol are undocumented, as well as from what firmware revision they were applied.

Anyway, I'll come back on this later on, hopefully today, and come with a satisfactory solution.

I'll look at the timestamps as well.

**Comment by AJRepo** [comment]
I just tested changing the if/elif/else test in `decode_spi_chunk()` to add one more test which increments pdb by 2 if it's not blank.  That solves the "Invalid SPI data chunk" error. 

The time changing to unixtime=0 happens when decode_spi_chunk is called again after completing a 4096 byte chunk. E.g.

```
pdb=4076,lnd=4096,LEN=14: 0 to 14= b'aa55001033333340e87291485a02'    time=2023-05-19 09:41:37
pdb=4090,lnd=4096,LEN=6: 0 to 14= b'aa5500099a99'     time=2023-05-19 09:41:37
pdb=0,lnd=4102,LEN=14: 0 to 14= b'aa5500099a991940d25798485a02'     time= 1969-12-31 18:00:00
```

At the beginning of decode_spi_chunk there is `ts=0` since then each data chunk starts with a timestamp record ts=0 until the parsing hit's the next timestamp record.  

I fixed that with adding a self._last_ts which holds the last ts before exiting the chunk. 

```
diff --git a/libgqe/protocol/GQRFC1701/v1_00/SPIR.py b/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
index 5bc6ce2..edd114c 100644
--- a/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
+++ b/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
@@ -19,6 +19,7 @@ if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth F
 import time
 import struct
 import datetime
+import binascii
 
 from libgqe.protocol.SPIR import SPIR as SPIR_PROTO
 
@@ -35,14 +36,21 @@ class SPIR(SPIR_PROTO):
         "AC EF",
         "Power Line"
     ]
+    _last_ts = 0
 
     def decode_spi_chunk(self, data):
+        debug = False
         pdb = 0  # Data byte pointer
         lnd = len(data)
-        ts = 0
+        ts = self._last_ts
         dt = datetime.datetime.now()
         while pdb < lnd:
+            if debug is True:
+                print(f"pdb={pdb},lnd={lnd},LEN={len(data[pdb:pdb+14])}: ", end="")
             if data[pdb:pdb+2] == b'\x55\xaa':    # Timestamp
+                if debug is True:
+                    print(f"DATE: pdb={pdb},lnd={lnd},LEN={len(data[pdb:pdb+14])}:", end='')
+                    print("0 to 8=", binascii.b2a_hex(data[pdb:pdb+8]))
                 if lnd - pdb >= 8:
                     tim = datetime.datetime(
                         ord(data[pdb+2:pdb+3]) + 100 * int(dt.year / 100),
@@ -54,10 +62,18 @@ class SPIR(SPIR_PROTO):
                     )
                     pdb += 8
                     ts = time.mktime(tim.timetuple())
+                    if debug is True:
+                        print(f"DATE SET: ts={ts}", end='')
+                        print("0 to 8=", binascii.b2a_hex(data[pdb:pdb+8]))
                 else:
+                    if debug is True:
+                        print(f"DATE BREAK: pdb={pdb},lnd={lnd},LEN={len(data[pdb:pdb+14])}:", end='')
+                        print("0 to 14=", binascii.b2a_hex(data[pdb:pdb+14]))
                     break
             elif data[pdb:pdb+2] == b'\xaa\x55':  # Data
                 if lnd - pdb >= 12:
+                    if debug is True:
+                        print("0 to 14=", binascii.b2a_hex(data[pdb:pdb+14]))
                     emf = (data[pdb+2] * 16 + data[pdb+3] >> 4) + (data[pdb+3] & 15) / 10
                     ef = struct.unpack('<f', data[pdb+4:pdb+8])[0]
                     rf = struct.unpack('<f', data[pdb+8:pdb+12])[0]
@@ -78,11 +94,21 @@ class SPIR(SPIR_PROTO):
                     pdb += 12
                     ts += 1
                 else:
+                    if debug is True:
+                        print(f"BREAK: pdb={pdb},lnd={lnd},LEN={len(data[pdb:pdb+14])}", end='')
+                        print("0 to 14=", binascii.b2a_hex(data[pdb:pdb+14]))
                     break
             elif data[pdb:pdb+1] == b'\xff':    # Empty data
                 self._chunk_remainder = b''
                 raise SPIR.EmptyDataError()
+            elif data[pdb:pdb+1] != []:
+                if debug is True:
+                    print(f"BREAK2: pdb={pdb},lnd={lnd}", end='')
+                    print("0 to 14=", binascii.b2a_hex(data[pdb:pdb+14]))
+                pdb += 2
+                break
             else:
                 raise ValueError('Invalid SPI data chunk at address 0x{:x} : {}'.format(pdb, data[pdb:pdb+2]))
 
+        self._last_ts=ts
         self._chunk_remainder = data[pdb:]
```

I can create a PR if you'd like

Two things in the above git diff that you can discard
1) I added `+import binascii`  which let's me dump the binary data as hex for debugging easily
2) I added a "debug" flag which calls binascii.b2a_hex() and writes to stdout so I can see, side by side, the csv export and the hex output  (write csv data to --out-file, write stdout to different file, column compare)

**Comment by AJRepo** [comment]
Here's a git diff without the debug code. Much easier to see the changes. 

```
diff --git a/libgqe/protocol/GQRFC1701/v1_00/SPIR.py b/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
index 5bc6ce2..9dbb1c4 100644
--- a/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
+++ b/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
@@ -35,11 +35,12 @@ class SPIR(SPIR_PROTO):
         "AC EF",
         "Power Line"
     ]
+    _last_ts = 0
 
     def decode_spi_chunk(self, data):
         pdb = 0  # Data byte pointer
         lnd = len(data)
-        ts = 0
+        ts = self._last_ts
         dt = datetime.datetime.now()
         while pdb < lnd:
             if data[pdb:pdb+2] == b'\x55\xaa':    # Timestamp
@@ -82,7 +83,11 @@ class SPIR(SPIR_PROTO):
             elif data[pdb:pdb+1] == b'\xff':    # Empty data
                 self._chunk_remainder = b''
                 raise SPIR.EmptyDataError()
+            elif data[pdb:pdb+1] != []:
+                pdb += 2
+                break
             else:
                 raise ValueError('Invalid SPI data chunk at address 0x{:x} : {}'.format(pdb, data[pdb:pdb+2]))
 
+        self._last_ts=ts
         self._chunk_remainder = data[pdb:]
```

**Comment by bernardn** [comment]
The commit b46403e527b488cfa062234dc5315424a82b196a adds support for the GQEMF390v2 where the data length is explicitly set to 14 bytes. Hopefully this will solve your issue.

Please now omit `--unit` and `--revision`, as the software should automatically recognize the v2 (or specify `--unit GQEMF390v2 --revision "Re 3.30"`).

**Comment by AJRepo** [comment]
This solves the invalid SPI data error. Nice!

The last thing is the timestamp going to 0 at each 4096 data chunk. Just need to have a self.last_ts to keep the ts record between chunks.  I fixed it where ts=0

```
diff --git a/libgqe/protocol/GQRFC1701/v1_00/SPIR.py b/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
index 7318639..0266036 100644
--- a/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
+++ b/libgqe/protocol/GQRFC1701/v1_00/SPIR.py
@@ -35,11 +35,12 @@ class SPIR(SPIR_PROTO):
         "AC EF",
         "Power Line"
     ]
+    _last_ts=0
 
     def decode_spi_chunk(self, data):
         pdb = 0  # Data byte pointer
         lnd = len(data)
-        ts = 0
+        ts = self._last_ts
         dt = datetime.datetime.now()
         while pdb < lnd:
             if data[pdb:pdb+2] == b'\x55\xaa':    # Timestamp
@@ -86,3 +87,4 @@ class SPIR(SPIR_PROTO):
                 raise ValueError('Invalid SPI data chunk at address 0x{:x} : {}'.format(pdb, data[pdb:pdb+2]))
 
         self._chunk_remainder = data[pdb:]
+        self._last_ts = ts
```

Let me know if you want a pull request on it?

**Comment by bernardn** [comment]
Thank you for the feedback, and for finding out the timestamp issue.

It'd be better to have an issue opened for that one. You can create a PR with your changes, but please move the `self._last_ts` variable initialization to the classes `__init__` methods, next to where `self._chunk_remainder` is initialized. Indeed, it's now placed placed as a constant.
